import json
import datetime
from sqlalchemy.orm import Session
from ..database.models import CSE, Finding, Alert, Case, Telemetry, RemediationAction

DISCLAIMER_TEXT = """
DISCLAIMER & SUPERVISORY NOTICE:
This supervisory report is generated by SAT-SA (Supervisory Analytics Tool for SOC Assessment) under the mandate of NCIIPC. 
The findings and metrics herein represent statistical, operational, and heuristic indicators designed to guide manual supervisory review. 
They do NOT constitute a definitive finding of non-compliance, breach, or compromise. The human supervisor remains the final decision-maker.
"""

def generate_executive_report_html(db: Session) -> str:
    cses = db.query(CSE).order_by(CSE.attention_score.desc()).all()
    findings = db.query(Finding).all()
    remediations = db.query(RemediationAction).all()
    
    total_alerts = db.query(Alert).count()
    total_cases = db.query(Case).count()
    total_findings = len(findings)
    high_findings = len([f for f in findings if f.severity in ["Critical", "High"]])
    neg_space_count = len([f for f in findings if f.finding_type == "Negative Space"])
    action_required_cses = len([c for c in cses if c.attention_score >= 50.0])

    top_entities_rows = ""
    for c in cses[:6]:
        status_color = "#e11d48" if c.attention_score >= 70 else ("#f59e0b" if c.attention_score >= 50 else "#10b981")
        top_entities_rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #334155; font-weight: bold;">{c.cse_id}</td>
            <td style="padding: 10px; border-bottom: 1px solid #334155;">{c.cse_name}</td>
            <td style="padding: 10px; border-bottom: 1px solid #334155;">{c.sector}</td>
            <td style="padding: 10px; border-bottom: 1px solid #334155;">{c.criticality}</td>
            <td style="padding: 10px; border-bottom: 1px solid #334155; font-weight: bold; color: {status_color}; font-size: 1.1em;">{c.attention_score} / 100</td>
            <td style="padding: 10px; border-bottom: 1px solid #334155;">
                <span style="background: {status_color}22; color: {status_color}; padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: 600;">
                    {c.review_status}
                </span>
            </td>
        </tr>
        """

    major_findings_html = ""
    for f in findings[:8]:
        sev_color = "#e11d48" if f.severity == "Critical" else ("#f59e0b" if f.severity == "High" else "#38bdf8")
        rec_actions = json.loads(f.recommended_actions_json) if f.recommended_actions_json else []
        actions_list = "".join([f"<li style='margin-bottom: 4px;'>{act}</li>" for act in rec_actions[:2]])
        
        major_findings_html += f"""
        <div style="background: #1e293b; border-left: 4px solid {sev_color}; padding: 15px; margin-bottom: 14px; border-radius: 0 6px 6px 0;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
                <span style="font-weight: bold; font-size: 1.05em; color: #f8fafc;">[{f.cse_id}] {f.title}</span>
                <span style="background: {sev_color}22; color: {sev_color}; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold;">{f.severity}</span>
            </div>
            <p style="color: #94a3b8; font-size: 0.9em; margin: 0 0 10px 0;">{f.description}</p>
            <div style="font-size: 0.85em; color: #cbd5e1; background: #0f172a; padding: 10px; border-radius: 4px;">
                <strong style="color: #38bdf8;">Recommended Supervisory Actions:</strong>
                <ul style="margin: 6px 0 0 18px; padding: 0;">{actions_list}</ul>
            </div>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NCIIPC SAT-SA Executive Supervisory Assessment Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background: #0b0f17;
            color: #f1f5f9;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }}
        .header {{
            border-bottom: 2px solid #38bdf8;
            padding-bottom: 20px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 30px;
        }}
        .kpi-card {{
            background: #1e293b;
            padding: 16px;
            border-radius: 8px;
            border: 1px solid #334155;
            text-align: center;
        }}
        .kpi-val {{
            font-size: 2em;
            font-weight: bold;
            color: #38bdf8;
            margin-top: 5px;
        }}
        .kpi-lbl {{
            font-size: 0.85em;
            color: #94a3b8;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: #1e293b;
            border-radius: 8px;
            overflow: hidden;
            margin-bottom: 30px;
        }}
        th {{
            background: #0f172a;
            padding: 12px 10px;
            text-align: left;
            font-size: 0.85em;
            color: #94a3b8;
            text-transform: uppercase;
            border-bottom: 2px solid #334155;
        }}
        .disclaimer-box {{
            background: #1e293b;
            border: 1px dashed #f59e0b;
            color: #fbbf24;
            padding: 16px;
            border-radius: 6px;
            font-size: 0.85em;
            margin-top: 40px;
        }}
        @media print {{
<<<<<<< HEAD
            /* The screen design uses a dark navy background with near-white
               text. Printed as-is, that means either a wall of dark ink or
               (with backgrounds suppressed by the print driver) near-white
               text on white paper. This block forces every background to
               white and every muted/light text color to a dark, legible
               one, while leaving the meaningful severity accent colors
               (the reds/oranges/blues that distinguish Critical/High/Medium
               findings) untouched, since those remain legible on paper and
               carry real information.
               !important is required here: the colors below are otherwise
               set as inline style="" attributes throughout this document,
               which always outrank a plain class or element rule. */
            * {{ box-shadow: none !important; text-shadow: none !important; }}
            body {{ background: #fff !important; color: #111827 !important; padding: 15px !important; }}
            .header {{ border-color: #94a3b8 !important; }}
            .kpi-card, table, .disclaimer-box, div {{ background: #fff !important; border-color: #cbd5e1 !important; }}
            .kpi-val {{ color: #0369a1 !important; }}
            .kpi-lbl {{ color: #475569 !important; }}
            th {{ background: #f1f5f9 !important; color: #334155 !important; }}
            td {{ border-color: #d1d5db !important; }}
            [style*="color: #f1f5f9"], [style*="color:#f1f5f9"],
            [style*="color: #cbd5e1"], [style*="color:#cbd5e1"],
            [style*="color: #94a3b8"], [style*="color:#94a3b8"] {{
                color: #334155 !important;
            }}
            [style*="background: #1e293b"], [style*="background:#1e293b"],
            [style*="background: #0f172a"], [style*="background:#0f172a"] {{
                background: #f8fafc !important;
            }}
            a {{ color: #0369a1 !important; }}
            @page {{ margin: 1.5cm; }}
=======
            body {{ background: #fff; color: #000; padding: 15px; }}
            .header {{ border-color: #000; }}
            .kpi-card, table, .disclaimer-box {{ background: #fff; border: 1px solid #ccc; color: #000; }}
            .kpi-val {{ color: #0284c7; }}
            th {{ background: #f1f5f9; color: #334155; }}
>>>>>>> 584f86a5a08d6aa3db9f3ba3b386a17085f0be83
        }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div style="font-size: 0.85em; text-transform: uppercase; color: #38bdf8; letter-spacing: 0.1em; font-weight: bold;">National Critical Information Infrastructure Protection Centre (NCIIPC)</div>
            <h1 style="margin: 6px 0 2px 0; font-size: 1.8em;">SAT-SA Executive Supervisory Assessment Report</h1>
            <div style="color: #94a3b8; font-size: 0.9em;">Reporting Period: 2026-Q3 | Generated: {datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}</div>
        </div>
        <div style="text-align: right;">
            <div style="background: #38bdf822; color: #38bdf8; border: 1px solid #38bdf8; padding: 6px 14px; border-radius: 6px; font-weight: bold; font-size: 0.9em;">SUPERVISORY OVERSIGHT</div>
        </div>
    </div>

    <div class="kpi-grid">
        <div class="kpi-card">
            <div class="kpi-lbl">Entities Analyzed</div>
            <div class="kpi-val">{len(cses)}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-lbl">Total Alerts Triaged</div>
            <div class="kpi-val">{total_alerts:,}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-lbl">Supervisory Signals</div>
            <div class="kpi-val">{total_findings}</div>
        </div>
        <div class="kpi-card">
            <div class="kpi-lbl">Requires Review</div>
            <div class="kpi-val" style="color: #e11d48;">{action_required_cses}</div>
        </div>
    </div>

    <h2 style="border-left: 4px solid #38bdf8; padding-left: 10px; font-size: 1.3em;">Priority Entity Attention Ranking</h2>
    <table>
        <thead>
            <tr>
                <th>Entity ID</th>
                <th>Entity Name</th>
                <th>Sector</th>
                <th>Criticality</th>
                <th>Attention Score</th>
                <th>Supervisory Status</th>
            </tr>
        </thead>
        <tbody>
            {top_entities_rows}
        </tbody>
    </table>

    <h2 style="border-left: 4px solid #38bdf8; padding-left: 10px; font-size: 1.3em;">Critical & High Severity Supervisory Findings</h2>
    {major_findings_html}

    <div class="disclaimer-box">
        <strong>OFFICIAL SUPERVISORY NOTICE:</strong><br/>
        {DISCLAIMER_TEXT.strip()}
    </div>
</body>
</html>
"""
    return html

def generate_cse_report_html(db: Session, cse_id: str) -> str:
    cse = db.query(CSE).filter(CSE.cse_id == cse_id).first()
    if not cse:
        return "<h1>CSE Not Found</h1>"

    findings = db.query(Finding).filter(Finding.cse_id == cse_id).all()
    remediations = db.query(RemediationAction).filter(RemediationAction.cse_id == cse_id).all()
    alerts_count = db.query(Alert).filter(Alert.cse_id == cse_id).count()
    cases_count = db.query(Case).filter(Case.cse_id == cse_id).count()
    crit_alerts = db.query(Alert).filter(Alert.cse_id == cse_id, Alert.severity == "Critical").all()
    crit_count = len(crit_alerts)
    unescalated_crit = len([a for a in crit_alerts if not a.escalated])

    findings_blocks = ""
    for f in findings:
        sev_color = "#e11d48" if f.severity == "Critical" else ("#f59e0b" if f.severity == "High" else "#38bdf8")
        rec_actions = json.loads(f.recommended_actions_json) if f.recommended_actions_json else []
        evidence = json.loads(f.evidence_json) if f.evidence_json else []
        metrics = json.loads(f.metrics_json) if f.metrics_json else {}

        actions_html = "".join([f"<li>{a}</li>" for a in rec_actions])
        
        evidence_preview = ""
        if evidence and isinstance(evidence, list):
            sample = evidence[:5]
            if isinstance(sample[0], dict):
                cols = list(sample[0].keys())[:4]
                header_th = "".join([f"<th style='padding: 6px; font-size: 0.75em; border: 1px solid #334155;'>{col}</th>" for col in cols])
                rows_td = ""
                for row in sample:
                    cells = "".join([f"<td style='padding: 6px; font-size: 0.75em; border: 1px solid #334155;'>{str(row.get(col, ''))}</td>" for col in cols])
                    rows_td += f"<tr>{cells}</tr>"
                evidence_preview = f"<table style='margin-top: 10px; width: 100%; border: 1px solid #334155;'><thead><tr>{header_th}</tr></thead><tbody>{rows_td}</tbody></table>"

        findings_blocks += f"""
        <div style="background: #1e293b; border-left: 4px solid {sev_color}; padding: 18px; margin-bottom: 20px; border-radius: 0 8px 8px 0;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                <span style="font-weight: bold; font-size: 1.1em; color: #f8fafc;">{f.title}</span>
                <span style="background: {sev_color}22; color: {sev_color}; padding: 3px 10px; border-radius: 4px; font-size: 0.85em; font-weight: bold;">{f.severity}</span>
            </div>
            <p style="color: #cbd5e1; font-size: 0.95em; margin: 0 0 12px 0;">{f.description}</p>
            
            {evidence_preview}

            <div style="margin-top: 14px; background: #0f172a; padding: 12px; border-radius: 6px; font-size: 0.9em;">
                <strong style="color: #10b981;">Corrective Action Plan (How to Heal):</strong>
                <ul style="margin: 8px 0 0 20px; padding: 0; color: #94a3b8;">{actions_html}</ul>
            </div>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NCIIPC Supervisory Dossier - {cse.cse_id}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #0b0f17;
            color: #f1f5f9;
            padding: 40px;
            line-height: 1.6;
        }}
        .header {{
            border-bottom: 2px solid #38bdf8;
            padding-bottom: 18px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
        }}
        .card-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 25px;
        }}
        .card {{
            background: #1e293b;
            padding: 16px;
            border-radius: 8px;
            border: 1px solid #334155;
            text-align: center;
        }}
        .card-val {{ font-size: 1.8em; font-weight: bold; color: #38bdf8; }}
        .card-lbl {{ font-size: 0.8em; color: #94a3b8; text-transform: uppercase; }}
        .disclaimer-box {{
            background: #1e293b;
            border: 1px dashed #f59e0b;
            color: #fbbf24;
            padding: 16px;
            border-radius: 6px;
            font-size: 0.85em;
            margin-top: 35px;
        }}
<<<<<<< HEAD
        @media print {{
            /* See the equivalent block in generate_executive_report_html for
               why this is necessary: inline style="" colors throughout this
               document need !important to be overridden for print. */
            * {{ box-shadow: none !important; text-shadow: none !important; }}
            body {{ background: #fff !important; color: #111827 !important; padding: 15px !important; }}
            .header {{ border-color: #94a3b8 !important; }}
            .card, .disclaimer-box, div {{ background: #fff !important; border-color: #cbd5e1 !important; }}
            .card-val {{ color: #0369a1 !important; }}
            .card-lbl {{ color: #475569 !important; }}
            th {{ background: #f1f5f9 !important; color: #334155 !important; border-color: #d1d5db !important; }}
            td {{ border-color: #d1d5db !important; }}
            [style*="color: #f1f5f9"], [style*="color:#f1f5f9"],
            [style*="color: #cbd5e1"], [style*="color:#cbd5e1"],
            [style*="color: #94a3b8"], [style*="color:#94a3b8"] {{
                color: #334155 !important;
            }}
            [style*="background: #1e293b"], [style*="background:#1e293b"],
            [style*="background: #0f172a"], [style*="background:#0f172a"] {{
                background: #f8fafc !important;
            }}
            a {{ color: #0369a1 !important; }}
            @page {{ margin: 1.5cm; }}
        }}
=======
>>>>>>> 584f86a5a08d6aa3db9f3ba3b386a17085f0be83
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div style="font-size: 0.85em; text-transform: uppercase; color: #38bdf8; letter-spacing: 0.1em; font-weight: bold;">NCIIPC Critical Sector Entity Audit Dossier</div>
            <h1 style="margin: 4px 0; font-size: 1.8em;">{cse.cse_name} ({cse.cse_id})</h1>
            <div style="color: #94a3b8; font-size: 0.9em;">Sector: {cse.sector} | Criticality: {cse.criticality} | Period: {cse.reporting_period}</div>
        </div>
        <div style="text-align: right;">
            <div style="font-size: 2.2em; font-weight: bold; color: {'#e11d48' if cse.attention_score >= 70 else '#f59e0b'};">{cse.attention_score} <span style="font-size: 0.5em; color: #94a3b8;">/ 100</span></div>
            <div style="font-size: 0.85em; color: #94a3b8;">Supervisory Attention Score</div>
        </div>
    </div>

    <div class="card-grid">
        <div class="card">
            <div class="card-lbl">Total Alerts</div>
            <div class="card-val">{alerts_count:,}</div>
        </div>
        <div class="card">
            <div class="card-lbl">Cases Investigated</div>
            <div class="card-val">{cases_count:,}</div>
        </div>
        <div class="card">
            <div class="card-lbl">Critical Alerts</div>
            <div class="card-val">{crit_count}</div>
        </div>
        <div class="card">
            <div class="card-lbl">Unescalated Criticals</div>
            <div class="card-val" style="color: #e11d48;">{unescalated_crit}</div>
        </div>
    </div>

    <h2 style="border-left: 4px solid #38bdf8; padding-left: 10px; font-size: 1.3em;">Supervisory Findings & Evidence</h2>
    {findings_blocks}

    <div class="disclaimer-box">
        <strong>SUPERVISORY CONFIDENTIALITY & DISCLAIMER:</strong><br/>
        {DISCLAIMER_TEXT.strip()}
    </div>
</body>
</html>
"""
    return html
